### ISSUE TITLE
CRASH opening huge mods

### ISSUE THREAD

**Issue by Falcata** [m-x-d/Simple-Quake-Launcher-2#12]
Trying selecting a huge mod like Slayer Testament the Sql Launcher crash and leave the desktop.
Qss 1.5.0 select engine.
Slayer testament mod - > select this and you have the crash.

**Comment by m-x-d** [comment]
Sorry, can't reproduce. Tried both "Slayer's Testaments 'TAG' release" and "Slayer's Testaments (with patch 4)" mod versions from moddb page, didn't get a crash on a 12 year old pc...

**Comment by Falcata** [comment]
I try the old version of your (SQL ver 1 ) and works perfectly, but with this version ( sql ver 2) try to read the file and then... "crash".  I dont know what version is this because ( Slayer's Testamente TAG) cames from other sources ( google drive).

**Comment by m-x-d** [comment]
Can you post google drive link to the version of the mod you are using?

**Comment by Falcata** [comment]
yep!.

https://drive.google.com/drive/folders/1OxkeBHM7XLBq9K0pYoV7Z3UwON5ha_bd

**Comment by m-x-d** [comment]
[Fixed](https://github.com/m-x-d/Simple-Quake-Launcher-2/releases/latest)!
