### ISSUE TITLE
[Feature Request] Quake Copper support

### ISSUE THREAD

**Issue by Zaratul555** [m-x-d/Simple-Quake-Launcher-2#4]
Like the title said. Please make support for Copper gameplay mod.

**Comment by m-x-d** [comment]
The mod doesn't seem to require any special Quake engine-side support, so I don't know what specific support do you expect to be implemented in SQL2...

**Comment by Zaratul555** [comment]
Nevermind. I tried to copy whole folder to Copper catalogue. I should copy mappack subfolders like with Arcane Dimensions. Sorry for commotion.
