### ISSUE TITLE
[Possible Bug] Upper limit to mod directories?

### ISSUE THREAD

**Issue by dumptruckDS** [m-x-d/Simple-Quake-Launcher-2#6]
I've added a few mods the past few days and no matter what I do the program will not recognize them. They are playable and have progs.dat files but refuse to show up in the list of mods. One of these is voidmod - attached. I'm stumped on this one. But my Quake directory is quite large.
![sql-issue](https://user-images.githubusercontent.com/16103297/115455665-19edfd80-a1d7-11eb-940b-7632703baed9.png)
[voidmod_20042021.zip](https://github.com/m-x-d/Simple-Quake-Launcher-2/files/6346307/voidmod_20042021.zip)

**Comment by m-x-d** [comment]
Addressed in v2.5. Previously, only mods containing maps were detected by the launcher.
